name: Azure Blob Check

on:
  workflow_dispatch:

jobs:
  check-blob:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Account list
        run: |
          az account list --output table

      - name: List Azure Storage Accounts
        run: |
          az storage account list --output table
    
      - name: List blobs in container
        run: |
          az storage blob list \
            --account-name ${{ vars.AZURE_STORAGE_ACCOUNT }} \
            --container-name ${{ vars.AZURE_CONTAINER_NAME }} \
            --auth-mode login \
            --output table
